name: Build and Deploy

on:
  push:
    tags:
      - v*
  
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      
      - name: Zip
        run: zip -r dist.zip dist
      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deploy
        uses: actions/deploy-pages@v2

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: |
            You can download the `dist.zip` file from the Assets section below to get the automatically built static resources and deploy them to your own server.

            Or, you can go to the [Online Demo](https://learn.oimaster.top/) to view the latest production version.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}