name: Build and Deploy

on:
  push:
    tags:
      - v*
  
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      - name: Deploy to Pages
        uses: actions/deploy-pages@v2
      - name: Zip
        run: zip -r dist.zip dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip
          tag_name: ${{ github.ref }}
          body: |
            You can download the `dist.zip` file from the Assets section below to get the automatically built static resources and deploy them to your own server.

            Or, you can go directly to the [Github Pages](${{ steps.deploy.outputs.url }}) to view the online demo.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}